services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  worker:
    build: .
    restart: unless-stopped
    command: celery -A cian_celery_tasks worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      TZ: TZ=Europe/Moscow
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM:-}
    # ðŸ‘‡ Ð¼Ð¾Ð½Ñ‚Ð¸Ñ€ÑƒÐµÐ¼ Ð¿Ñ€Ð¾ÐµÐºÑ‚
    volumes:
      - ./:/app
    depends_on:
      - redis

  beat:
    build: .
    restart: unless-stopped
    command: celery -A cian_celery_tasks beat --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      TZ: TZ=Europe/Moscow
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM:-}
    # ðŸ‘‡ Ñ‚Ð¾Ð¶Ðµ Ð¼Ð¾Ð½Ñ‚Ð¸Ñ€ÑƒÐµÐ¼ Ð¿Ñ€Ð¾ÐµÐºÑ‚
    volumes:
      - ./:/app
    depends_on:
      - redis